pipeline {
    agent any

    parameters {
        string(name: 'TAG', defaultValue: '@user', description: 'Tag to execute')
    }

    tools {
        maven 'maven_3.8.3'
    }

    stages {
        stage('Test') {
            steps {
                script{
                    sh """
                        cd siigo_backend/
                        mvn clean verify -Dcucumber.filter.tags=${params.TAG}
                    """
                }
            }
        }
    }

    post {
        always {
            publishHTML target: [
                allowMissing: false,
                alwaysLinkToLastBuild: false,
                keepAll: true,
                reportDir: 'siigo_backend/target/site/serenity',
                reportFiles: 'index.html',
                reportName: 'Serenity Report'
            ]

            archiveArtifacts artifacts: 'siigo_backend/target/site/serenity/serenity-summary.html'
        }
    }
}