pipeline {
    agent any

    parameters {
        booleanParam(name: 'EDGE', defaultValue: true, description: 'Run tests on Edge')
        booleanParam(name: 'CHROME', defaultValue: true, description: 'Run tests on Chrome')
        booleanParam(name: 'FIREFOX', defaultValue: true, description: 'Run tests on Firefox')
    }

    tools {
        maven 'maven_3.8.3'
    }

    stages {

        stage('Generate Docker Compose Override') {
            steps {
                script {
                    def services = []
                    if (params.EDGE) {
                        services.add('edge')
                    }
                    if (params.CHROME) {
                        services.add('chrome')
                    }
                    if (params.FIREFOX) {
                        services.add('firefox')
                    }

                    def overrideContent = """
                    services:
                    """
                    services.each { service ->
                        overrideContent += """
                          ${service}:
                            image: selenium/node-${service}:4.29.0-20250222
                            shm_size: 2gb
                            depends_on:
                              - selenium-hub
                            environment:
                              - SE_EVENT_BUS_HOST=selenium-hub
                              - SE_EVENT_BUS_PUBLISH_PORT=4442
                              - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
                        """
                    }

                    writeFile file: 'siigo_frontend/docker-compose.override.yml', text: overrideContent
                }
            }
        }

        stage('Start Selenium Grid') {
            steps {
                script {
                    sh """
                        cd siigo_frontend/
                        docker-compose up -d
                    """
                }
            }
        }

        stage('Run Tests') {
            parallel {
                stage('Edge Tests') {
                    when {
                        expression { params.EDGE }
                    }
                    steps {
                        script {
                            sh """
                                cd siigo_frontend/
                                mvn clean verify -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub -Dwebdriver.remote.driver=edge
                            """
                        }
                    }
                }
                stage('Chrome Tests') {
                    when {
                        expression { params.CHROME }
                    }
                    steps {
                        script {
                            sh """
                                cd siigo_frontend/
                                mvn clean verify -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub -Dwebdriver.remote.driver=chrome
                            """
                        }
                    }
                }
                stage('Firefox Tests') {
                    when {
                        expression { params.FIREFOX }
                    }
                    steps {
                        script {
                            sh """
                                cd siigo_frontend/
                                mvn clean verify -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub -Dwebdriver.remote.driver=firefox
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                sh """
                    cd siigo_frontend/
                    docker-compose down
                """
            }

            publishHTML target: [
                allowMissing: false,
                alwaysLinkToLastBuild: false,
                keepAll: true,
                reportDir: 'siigo_frontend/target/site/serenity',
                reportFiles: 'index.html',
                reportName: 'Serenity Report'
            ]

            archiveArtifacts artifacts: 'siigo_frontend/target/site/serenity/serenity-summary.html'
        }
    }
}